## code to prepare `delini_review` dataset goes here
# Delini Farmstead review example ----------------------------------------

delini_review <- tibble::tribble(
  ~evidence_id,
  ~thumbnail_url,
  ~evidence_url,
  ~subject,
  ~label_en,
  ~description_en,
  ~label_hu,
  ~description_hu,
  ~inventory_number,
  ~instance_of,
  ~evidence_type,
  ~held_by,
  "P7101556",
  "https://betwixt.dataobservatory.eu/articles/images/delini/artefacts/P7101565_thumbnail.jpg",
  "https://example.com/delini.html",
  "[image shown]",
  "farmhouse (LEBM)",
  "the farmhouse of the Delini farmstead",
  "lakóépület (LEBM)",
  "a Delini tanya lakóépülete",
  "delin 13",
  "farmhouse",
  "artefact photograph",
  "The Ethnographic Open-Air Museum of Latvia",
  "P7101565",
  "https://betwixt.dataobservatory.eu/articles/images/delini/artefacts/P7101561_thumbnail.jpg",
  NA_character_,
  "[image shown]",
  "sash (LEBM)",
  "a tablet-woven sash in the master bedroom of the Delini farmhouse",
  "öv (LEBM)",
  NA_character_,
  "pn 8246",
  "tablet-woven sash",
  "artefact photograph",
  "The Ethnographic Open-Air Museum of Latvia",
  "P7101561",
  "https://betwixt.dataobservatory.eu/articles/images/delini/artefacts/P7101556_thumbnail.jpg",
  NA_character_,
  "[image shown]",
  "bed (LEBM)",
  "a bed in the master bedroom of the Delini farmhouse",
  "ágy (LEBM)",
  NA_character_,
  NA_character_,
  "bed",
  "artefact photograph",
  "The Ethnographic Open-Air Museum of Latvia",
  "P7101590",
  "https://betwixt.dataobservatory.eu/articles/images/delini/records/P7101590_thumbnail.jpg",
  NA_character_,
  "[image shown]",
  "Delini farmhouse photographs",
  "a record containing two photographs of the Delini farmhouse",
  "Delini lakóépület fényképei",
  NA_character_,
  NA_character_,
  "photographic record",
  "record",
  "The Ethnographic Open-Air Museum of Latvia",
  "P7101623",
  "https://betwixt.dataobservatory.eu/articles/images/delini/records/P7101623_thumbnail.jpg",
  NA_character_,
  "[image shown]",
  "Delini farmhouse floor plan",
  "a floor plan of the Delini farmhouse prepared for its reconstruction",
  "Delini lakóépület alaprajza",
  NA_character_,
  NA_character_,
  "floor plan",
  "record",
  "The Ethnographic Open-Air Museum of Latvia"
)

usethis::use_data(delini_review, overwrite = TRUE)
