## code to prepare `delini` dataset goes here

delini <- tibble::tribble(
  ~row_number,
  ~evidence_url,
  ~evidence_text,
  ~label,
  ~description,
  ~col_1,
  ~col_1_range,
  ~col_1_definition,
  ~col_2,
  ~col_2_range,
  ~col_2_definition,
  ~col_3,
  ~col_3_range,
  ~col_3_definition,
  ~context_1,
  1,
  "https://betwixt.dataobservatory.eu/articles/images/delini/artefacts/P7101565_thumbnail.jpg",
  "P7101565",
  "Delini farmstead",
  "the farmhouse of the Delini farmstead",
  "fuds:Q7328",
  NA_character_,
  NA_character_,
  "farmhouse",
  "farmhouse | tablet-woven sash | bed | record | Other…",
  "https://www.wikidata.org/wiki/Property:P31",
  "Livonians",
  "Livonians | Latvians | Other… | Do not know | None of these",
  NA_character_,
  "The Ethnographic Open-Air Museum of Latvia",
  2,
  "https://betwixt.dataobservatory.eu/articles/images/delini/artefacts/P7101561_thumbnail.jpg",
  "P7101561",
  "tablet-woven sash (PLM 1234)",
  "a tablet-woven sash in the master bedroom of the Delini farmhouse",
  "tablet-woven sash (PLM 1234)",
  NA_character_,
  NA_character_,
  "tablet-woven sash",
  "farmhouse | tablet-woven sash | bed | record | Other…",
  "https://www.wikidata.org/wiki/Property:P31",
  "Livonians",
  "Livonians | Latvians | Other… | Do not know | None of these",
  NA_character_,
  "The Ethnographic Open-Air Museum of Latvia",
  3,
  "https://betwixt.dataobservatory.eu/articles/images/delini/artefacts/P7101556_thumbnail.jpg",
  "P7101556",
  "bed (PLM 7201)",
  "a bed in the master bedroom of the Delini farmhouse",
  "bed (PLM 7201)",
  NA_character_,
  NA_character_,
  "bed",
  "farmhouse | tablet-woven sash | bed | record | Other…",
  "https://www.wikidata.org/wiki/Property:P31",
  "Livonians",
  "Livonians | Latvians | Other… | Do not know | None of these",
  NA_character_,
  "The Ethnographic Open-Air Museum of Latvia",
  4,
  "https://betwixt.dataobservatory.eu/articles/images/delini/records/P7101590_thumbnail.jpg",
  "P7101590",
  "record (LOAM/archive/box23/12)",
  "a record containing two photographs of the Delini farmhouse",
  "record (LOAM/archive/box23/12)",
  NA_character_,
  NA_character_,
  "record",
  "farmhouse | tablet-woven sash | bed | record | Other…",
  "https://www.wikidata.org/wiki/Property:P31",
  "Livonians",
  "Livonians | Latvians | Other… | Do not know | None of these",
  NA_character_,
  "The Ethnographic Open-Air Museum of Latvia",
  5,
  "https://betwixt.dataobservatory.eu/articles/images/delini/records/P7101623_thumbnail.jpg",
  "P7101623",
  "record (LOAM/archive/box23/13)",
  "a floor plan of the Delini farmhouse prepared for its reconstruction",
  "record (LOAM/archive/box23/13)",
  NA_character_,
  NA_character_,
  "record",
  "farmhouse | tablet-woven sash | bed | record | Other…",
  "https://www.wikidata.org/wiki/Property:P31",
  "Livonians",
  "Livonians | Latvians | Other… | Do not know | None of these",
  NA_character_,
  "The Ethnographic Open-Air Museum of Latvia"
)

delini$row_number <- as.integer(delini$row_number)

usethis::use_data(delini, overwrite = TRUE)
