#' Assemble a standalone HTML review document
#' @keywords internal
assemble_review_html <- function(
  title,
  description,
  table_html,
  css,
  js,
  reviewer_name,
  reviewer_iri,
  project_id,
  table_id,
  sequence,
  original_filename,
  original_created_at,
  filename_stem,
  review_comment_html,
  provenance_footer
) {
  html <- paste0(
    "<!doctype html>\n",
    '<html lang="en">\n',
    "<head>\n",
    '<meta charset="utf-8">\n',
    '<meta name="viewport" ',
    'content="width=device-width, initial-scale=1">\n',
    "<title>", escape_html(title), "</title>\n",
    "<style>\n", css, "\n</style>\n",
    "</head>\n",
    "<body>\n",
    "<main>\n",
    '<header class="review-header">\n',
    "<h1>", escape_html(title), "</h1>\n",
    '<p class="instructions">',
    escape_html(description),
    "</p>\n",
    "</header>\n",
    '<div class="table-wrap">\n',
    table_html,
    "\n</div>\n",
    '<div class="footer">\n',
    '<span id="summary"></span>\n',
    "</div>\n",
    '<section class="review-meta">\n',
    "<h2>Review metadata</h2>\n",
    '<div class="reviewer-bottom">\n',
    "<label>Reviewer",
    '<input id="reviewer-name" type="text" value="',
    escape_html(reviewer_name), '">',
    "</label>\n",
    "<label>Reviewer email",
    '<input id="reviewer-email" type="email">',
    "</label>\n",
    "<label>Reviewer IRI (e.g. ORCID, ISNI, Wikidata)",
    '<input id="reviewer-iri" class="reviewer-iri-input" ',
    'type="text" value="',
    escape_html(reviewer_iri), '">',
    "</label>\n",
    "<label>Project ID",
    '<input id="project-id" type="text" value="',
    escape_html(project_id), '" readonly>',
    "</label>\n",
    "<label>Table ID",
    '<input id="table-id" type="text" value="',
    escape_html(table_id), '" readonly>',
    "</label>\n",
    "<label>State sequence",
    '<input id="review-sequence" type="number" value="',
    sequence, '" readonly>',
    "</label>\n",
    "<label>Original filename",
    '<input id="original-filename" type="text" value="',
    escape_html(original_filename), '" readonly>',
    "</label>\n",
    "<label>Filename",
    '<input id="review-filename" type="text" value="',
    escape_html(original_filename), '" readonly>',
    "</label>\n",
    "<label>Original created at",
    '<input id="original-created-at" type="text" value="',
    original_created_at, '" readonly>',
    "</label>\n",
    "<label>Started at",
    '<input id="review-started-at" type="text" readonly>',
    "</label>\n",
    "<label>Last saved at",
    '<input id="review-last-saved-at" type="text" readonly>',
    "</label>\n",
    "<label>Ended at",
    '<input id="review-ended-at" type="text" readonly>',
    "</label>\n",
    "<label>Status",
    '<input id="review-status" type="text" ',
    'value="in-progress" readonly>',
    "</label>\n",
    "</div>\n",

    # Add the optional review-level comment.
    review_comment_html,

    # Store the filename stem as non-editable process metadata.
    '<input id="filename-stem" type="hidden" value="',
    escape_html(filename_stem), '">\n',
    '<div class="save-actions">\n',
    '<button id="save-draft" type="button">',
    "Save draft",
    "</button>\n",
    '<button id="save-final" type="button">',
    "Finalise review",
    "</button>\n",
    "</div>\n",
    '<div id="save-status" class="save-status"></div>\n',
    "</section>\n",
    provenance_footer,
    '<footer class="site-footer">',
    "Created with Betwixt semantic review \u00b7 ",
    '<a href="https://github.com/dataobservatory-eu/betwixt" ',
    'target="_blank" rel="noopener">GitHub</a>',
    " \u00b7 ",
    '<a href="https://doi.org/10.5281/zenodo.22091535" ',
    'target="_blank" rel="noopener">',
    "doi:10.5281/zenodo.22091535</a>",
    "</footer>\n",
    "</main>\n",
    "<script>\n", js, "\n</script>\n",
    "</body>\n",
    "</html>\n"
  )

  html
}
