#' Render a Betwixt review interface
#'
#' Renders a human-readable review interface from a rectangular dataset.
#'
#' A review interface may contain four blocks:
#'
#' * **evidence**, containing media or a source URL inspected by the reviewer;
#' * **descriptive metadata**, containing information that may be displayed
#'   or edited without constituting an epistemic review decision;
#' * **semantic assertions**, containing the information under review; and
#' * **context**, containing additional information that supports the review.
#'
#' The columns belonging to these blocks are specified explicitly. Their
#' roles are not inferred from column names.
#'
#' Long and wide reviews are alternative human-readable projections of
#' semantic assertions. They do not define different semantic models.
#'
#' @param claim A data frame containing the material to render.
#' @param range Optional data frame defining proposed values for reviewable
#'   assertions.
#' @param evidence_media_file Optional character string naming the column
#'   containing the media resource presented as evidence.
#' @param evidence_url Optional character string naming the column containing
#'   a URL to supporting evidence.
#' @param descriptive Optional character vector naming columns presented as
#'   descriptive metadata.
#' @param assertions Optional character vector naming columns presented as
#'   reviewable assertions.
#' @param context Optional character vector naming columns presented as
#'   contextual information.
#' @param con Optional output connection or file path. If `NULL`, return the
#'   rendered HTML as a character string.
#' @param title Character string giving the review title.
#' @param description Character string describing the review task.
#' @param betwixt_id Character string identifying the review artefact.
#' @param template Character string identifying the review template. Must be
#'   `"long_review"` or `"wide_review"`.
#'
#' @details
#' In a long review, `assertions` identifies the assertion components exposed
#' as columns. For example, `c("subject", "predicate", "value")` exposes a
#' complete elementary assertion, while `c("predicate", "value")` may be used
#' when the subject is implicit in the evidence under review.
#'
#' A long review may also expose multiple proposed values, for example
#' `c("predicate", "value1", "value2")`.
#'
#' In a wide review, each column named by `assertions` represents a predicate
#' and its cells contain the corresponding reviewable values.
#'
#' Sequential row numbers are generated by the renderer. They are part of the
#' review interface and do not need to be present in `claim`.
#'
#' @return If `con` is `NULL`, a character string containing the rendered
#'   HTML. Otherwise, `con` is returned invisibly.
#'
#' @export
betwixt_render <- function(
  claim,
  range = NULL,
  evidence_media_file = NULL,
  evidence_url = NULL,
  descriptive = NULL,
  assertions = NULL,
  context = NULL,
  con = NULL,
  title = "Betwixt Review",
  description = "Please review the following claims.",
  betwixt_id = "P1234",
  template = "long_review"
) {
  # Validate the input data.
  if (!is.data.frame(claim)) {
    stop("claim must be a data frame.", call. = FALSE)
  }

  # Register the supported review projections.
  templates <- list(
    long_review = c(
      template = "long_review/template_long.mustache",
      style = "long_review/long_style.css",
      script = "long_review/long_script.js"
    ),
    wide_review = c(
      template = "wide_review/template_wide.mustache",
      style = "wide_review/wide_style.css",
      script = "wide_review/wide_script.js"
    )
  )

  # Validate the requested projection.
  if (!template %in% names(templates)) {
    stop(
      "Unknown template: '", template,
      "'. Expected 'long_review' or 'wide_review'.",
      call. = FALSE
    )
  }

  # Validate explicitly selected interface columns.
  selected_columns <- c(
    evidence_media_file, evidence_url,
    descriptive, assertions, context
  )

  missing_columns <- setdiff(
    selected_columns,
    names(claim)
  )

  if (length(missing_columns)) {
    label <- if (length(missing_columns) == 1) {
      "Unknown column: "
    } else {
      "Unknown columns: "
    }

    stop(
      label,
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }

  # Locate the files belonging to the selected projection.
  template_files <- templates[[template]]

  template_file <- system.file(
    template_files["template"],
    package = "betwixt"
  )

  style_file <- system.file(
    template_files["style"],
    package = "betwixt"
  )

  script_file <- system.file(
    template_files["script"],
    package = "betwixt"
  )

  # Fail early when an installed rendering resource is missing.
  if (!nzchar(template_file)) {
    stop(
      "Template file not found for '",
      template,
      "'.",
      call. = FALSE
    )
  }

  if (!nzchar(style_file)) {
    stop(
      "Style file not found for '",
      template,
      "'.",
      call. = FALSE
    )
  }

  if (!nzchar(script_file)) {
    stop(
      "Script file not found for '",
      template,
      "'.",
      call. = FALSE
    )
  }

  # Read the rendering resources into the document context.
  template_html <- paste(
    readLines(
      template_file,
      warn = FALSE,
      encoding = "UTF-8"
    ),
    collapse = "\n"
  )

  betwixt_css <- paste(
    readLines(
      style_file,
      warn = FALSE,
      encoding = "UTF-8"
    ),
    collapse = "\n"
  )

  betwixt_js <- paste(
    readLines(
      script_file,
      warn = FALSE,
      encoding = "UTF-8"
    ),
    collapse = "\n"
  )

  # Prepare each source row for the Mustache template.
  claims <- lapply(seq_len(nrow(claim)), function(i) {
    media_value <- ""

    if (!is.null(evidence_media_file)) {
      value <- claim[[evidence_media_file]][i]

      if (!is.na(value)) {
        media_value <- as.character(value)
      }
    }

    evidence_url_value <- ""

    if (!is.null(evidence_url)) {
      value <- claim[[evidence_url]][i]

      if (!is.na(value)) {
        evidence_url_value <- as.character(value)
      }
    }

    # Prepare editable descriptive metadata.
    descriptions <- lapply(descriptive, function(column) {
      value <- claim[[column]][i]

      list(
        name = column,
        value = if (is.na(value)) "" else as.character(value),
        is_description = grepl("^description", column)
      )
    })

    # Prepare reviewable assertions according to the projection.
    assertion_values <- lapply(assertions, function(column) {
      value <- claim[[column]][i]

      range_type <- assertion_range_type(
        column = column,
        template = template
      )

      # Prepare the range according to the review projection.
      if (is.null(range_type)) {
        column_range <- list()
      } else if (template == "wide_review") {
        column_range <- prepare_range(
          range = range,
          type = range_type,
          field = column,
          current = value
        )
      } else {
        column_range <- prepare_range(
          range = range,
          type = range_type
        )
      }

      list(
        name = column,
        heading = column,
        value = if (is.na(value)) "" else as.character(value),
        range = column_range,
        has_range = length(column_range) > 0
      )
    })

    # Prepare non-reviewable contextual information.
    context_values <- lapply(context, function(column) {
      value <- claim[[column]][i]

      list(
        name = column,
        value = if (is.na(value)) "" else as.character(value)
      )
    })

    # Assemble one row of the rendering context.
    list(
      row_number = i,
      evidence_media_file = media_value,
      has_evidence_media = nzchar(media_value),
      evidence_url = evidence_url_value,
      has_evidence_url = nzchar(evidence_url_value),
      descriptions = descriptions,
      assertions = assertion_values,
      context = context_values
    )
  })

  # Assemble the complete Mustache rendering context.
  render_context <- list(
    has_evidence = !is.null(evidence_media_file) ||
      !is.null(evidence_url),
    description_columns = lapply(
      descriptive,
      function(column) list(heading = column)
    ),
    assertion_columns = lapply(
      assertions,
      function(column) list(heading = column)
    ),
    context_columns = lapply(
      context,
      function(column) list(name = column)
    ),
    claims = claims,
    title = title,
    description = description,
    betwixt_id = betwixt_id,
    betwixt_generated_at = format(
      Sys.time(),
      "%Y-%m-%dT%H:%M:%S%z"
    ),
    betwixt_css = betwixt_css,
    betwixt_js = betwixt_js
  )

  # Render the self-contained HTML review artefact.
  html <- whisker::whisker.render(
    template_html,
    render_context
  )

  # Return HTML directly unless an output destination was supplied.
  if (is.null(con)) {
    return(html)
  }

  cat(
    html,
    "\n",
    file = con,
    sep = ""
  )

  invisible(con)
}
